import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { build as viteBuild, createServer as viteCreateServer } from 'vite';
import { parseDocsDirectory, generateLlmsTxt, generateLlmsFullTxt } from './parser.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const packageRootDir = path.resolve(__dirname, '..');
const templateDir = path.join(packageRootDir, 'template');

function escapeHtml(str) {
  if (str == null) return '';
  return String(str)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

export function prepareStaging(inputDir, options = {}) {
  const resolvedInput = path.resolve(inputDir);
  if (!fs.existsSync(resolvedInput)) {
    throw new Error(`Input documentation directory not found: ${resolvedInput}`);
  }

  // Staging cache directory
  const stagingDir = path.resolve(process.cwd(), '.docs-gen-cache');
  if (!fs.existsSync(stagingDir)) {
    fs.mkdirSync(stagingDir, { recursive: true });
  }

  // Read config file if present (docs.config.json)
  let fileConfig = {};
  const configPath = options.config
    ? path.resolve(options.config)
    : path.join(resolvedInput, 'docs.config.json');
  if (fs.existsSync(configPath)) {
    try {
      fileConfig = JSON.parse(fs.readFileSync(configPath, 'utf-8'));
    } catch (e) {
      console.warn(`Warning: Could not parse config file at ${configPath}:`, e.message);
    }
  }

  const mergedOptions = {
    title: options.title || fileConfig.title || 'Documentation',
    description: options.description || fileConfig.description || 'Material Design 3 Documentation',
    githubUrl: options.github || options.githubUrl || fileConfig.githubUrl || '',
    baseUrl: options.base || options.baseUrl || fileConfig.baseUrl || './'
  };

  // Parse markdown documentation
  const parsedData = parseDocsDirectory(resolvedInput, mergedOptions);

  // Copy template files to staging
  fs.copyFileSync(path.join(templateDir, 'docs.css'), path.join(stagingDir, 'docs.css'));
  fs.copyFileSync(path.join(templateDir, 'docs.js'), path.join(stagingDir, 'docs.js'));

  // Generate index.html with replaced metadata
  let indexHtml = fs.readFileSync(path.join(templateDir, 'index.html'), 'utf-8');
  indexHtml = indexHtml
    .replace(/__SITE_TITLE__/g, escapeHtml(parsedData.siteConfig.title))
    .replace(/__SITE_DESCRIPTION__/g, escapeHtml(parsedData.siteConfig.description))
    .replace(/__GITHUB_URL__/g, escapeHtml(parsedData.siteConfig.githubUrl || ''));
  fs.writeFileSync(path.join(stagingDir, 'index.html'), indexHtml, 'utf-8');

  // Write docs-data.js module
  const docsDataJs = `// Auto-generated by docs-gen. Do not edit manually.
export const SITE_CONFIG = ${JSON.stringify(parsedData.siteConfig, null, 2)};
export const CATEGORIES = ${JSON.stringify(parsedData.categories, null, 2)};
export const DOCS = ${JSON.stringify(parsedData.docs, null, 2)};
export const SEARCH_INDEX = ${JSON.stringify(parsedData.searchIndex, null, 2)};
`;
  fs.writeFileSync(path.join(stagingDir, 'docs-data.js'), docsDataJs, 'utf-8');

  // Generate llms.txt & llms-full.txt in public/ so Vite serves them at /llms.txt
  const publicDir = path.join(stagingDir, 'public');
  if (!fs.existsSync(publicDir)) {
    fs.mkdirSync(publicDir, { recursive: true });
  }

  let llmsTxt = '';
  const customLlmsPath = path.join(resolvedInput, 'llms.txt');
  if (fs.existsSync(customLlmsPath)) {
    llmsTxt = fs.readFileSync(customLlmsPath, 'utf-8');
  } else {
    llmsTxt = generateLlmsTxt(parsedData.siteConfig, parsedData.categories, parsedData.docs);
  }
  const llmsFullTxt = generateLlmsFullTxt(parsedData.siteConfig, parsedData.docs);

  fs.writeFileSync(path.join(publicDir, 'llms.txt'), llmsTxt, 'utf-8');
  fs.writeFileSync(path.join(publicDir, 'llms-full.txt'), llmsFullTxt, 'utf-8');

  return {
    stagingDir,
    parsedData,
    llmsTxt,
    llmsFullTxt
  };
}

export async function buildSite(options = {}) {
  const inputDir = options.input || 'docs';
  const outputDir = path.resolve(process.cwd(), options.output || '_site');
  const base = options.base || './';

  console.log(`\nGenerating documentation from: ${path.resolve(inputDir)}`);
  const { stagingDir, parsedData, llmsTxt, llmsFullTxt } = prepareStaging(inputDir, options);

  console.log(`Found ${parsedData.docs.length} documentation pages across ${parsedData.categories.length} categories.`);
  parsedData.categories.forEach(cat => {
    console.log(`   - ${cat.name} (${cat.items.length} pages)`);
  });

  console.log(`\nBuilding static assets with Vite (base: "${base}")...`);
  await viteBuild({
    root: stagingDir,
    base,
    build: {
      outDir: outputDir,
      emptyOutDir: true,
      assetsDir: 'assets'
    },
    logLevel: 'info'
  });

  // Ensure llms.txt and llms-full.txt are present at the root of the output directory
  fs.writeFileSync(path.join(outputDir, 'llms.txt'), llmsTxt, 'utf-8');
  fs.writeFileSync(path.join(outputDir, 'llms-full.txt'), llmsFullTxt, 'utf-8');

  console.log(`Generated llms.txt and llms-full.txt for LLMs and AI crawlers.`);
  console.log(`\nDocumentation successfully built to: ${outputDir}`);
  console.log(`Ready for GitHub Pages deployment!\n`);

  return { outputDir, parsedData };
}

export async function startDevServer(options = {}) {
  const inputDir = options.input || 'docs';
  const port = options.port || 3000;

  console.log(`\nStarting documentation dev server from: ${path.resolve(inputDir)}`);
  const { stagingDir } = prepareStaging(inputDir, options);

  const server = await viteCreateServer({
    root: stagingDir,
    server: {
      port,
      open: options.open ?? true
    }
  });

  await server.listen();
  server.printUrls();

  // Watch input directory for markdown changes
  const resolvedInput = path.resolve(inputDir);
  console.log(`Watching for changes in ${resolvedInput}...\n`);

  let debounceTimer = null;
  fs.watch(resolvedInput, { recursive: true }, (eventType, filename) => {
    if (!filename || !/\.md$|\.json$/i.test(filename)) return;
    clearTimeout(debounceTimer);
    debounceTimer = setTimeout(() => {
      try {
        console.log(`Detected change in ${filename}, updating docs...`);
        prepareStaging(inputDir, options);
        // Invalidate docs-data.js module in Vite server
        const moduleNode = server.moduleGraph.getModuleById(path.join(stagingDir, 'docs-data.js'));
        if (moduleNode) {
          server.moduleGraph.invalidateModule(moduleNode);
        }
        server.ws.send({ type: 'full-reload' });
      } catch (err) {
        console.error('Error updating docs:', err.message);
      }
    }, 200);
  });

  return server;
}

